export enum SuccessCodes{
    SUCCESS_MAESTROS_FOUND = "SUC001",
    SUCCESS_UPLOAD = "SUC002",
    SUCCESS_DATA_REQUEST_VALID = "SUC003",
    SUCCESS_CONFIG_SAVED="SUC004",
    SUCCESS_RENAME_FOLDER="SUC005",
    SUCCESS_CANCEL_MERGE="SUC006",
    SUCCESS_MERGE="SUC007",
    SUCCESS_TREE_GENERATE="SUC008"
};